language: node_js

sudo: false

os:
  - linux
  - windows

node_js:
  - "6"
  - "8"
  - "9"
  - "10"
  - "11"

cache: npm

jobs:
  include:
    - stage: type checks
      os: linux
      node_js: "8"
      script: npm run dtslint && npm run flow
